export const FETCH_IMAGES_REQUEST = 'FETCH_IMAGES_REQUEST';
export const FETCH_IMAGES_RESPONSE = 'FETCH_IMAGES_RESPONSE';
export const FETCH_IMAGES_ERROR = 'FETCH_IMAGES_ERROR';
export const IMAGE_SEARCH_REQUEST = 'IMAGE_SEARCH_REQUEST';
export const IMAGE_SEARCH_RESPONSE = 'IMAGE_SEARCH_RESPONSE';
export const SEARCH_IMAGES_REQUEST = 'SEARCH_IMAGES_REQUEST';
export const SEARCH_IMAGES_RESPONSE = 'SEARCH_IMAGES_RESPONSE';
export const REFETCH_IMAGES_RESPONSE = 'REFETCH_IMAGES_RESPONSE';